### ISSUE TITLE
DoH and DoT

### ISSUE THREAD

**Issue by hybtoy** [LiveChief/unbound-dns-resolver#2]
@LiveChief 
Hello, what about DNS-over-TLS and DNS-over-HTTPS in unbound? 
Is it possible to do it via script?
Thanks.

**Comment by LiveChief** [comment]
@hybtoy
`Client (DNSSEC) > Unbound > (DNS OVER TLS) > Google`
```
  echo "server:
  num-threads: 4
  verbosity: 1
  root-hints: "/etc/unbound/root.hints"
  auto-trust-anchor-file: "/var/lib/unbound/root.key"
  interface: 0.0.0.0
  interface: ::0
  max-udp-size: 3072
  access-control: 0.0.0.0/0                 refuse
  access-control: 10.8.0.0/24               allow
  private-address: 10.8.0.0/24
  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  harden-referral-path: yes
  unwanted-reply-threshold: 10000000
  val-log-level: 1
  cache-min-ttl: 1800
  cache-max-ttl: 14400
  prefetch: yes
  qname-minimisation: yes
  prefetch-key: yes
  forward-zone:
  name: "."
  forward-tls-upstream: yes
  forward-addr: 8.8.8.8@853
  forward-addr: 8.8.4.4@853
  forward-addr: 2001:4860:4860::8888@853
  forward-addr: 2001:4860:4860::8844@853" > /etc/unbound/unbound.conf
```

or 
do you want this?

`Client (DNS OVER TLS) > Unbound > (DNS OVER TLS) > Google`

Gonna take a little bit more time.
